services:
  backend:
    build: .
    container_name: communalert_backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - mysql-db
    volumes:
      - ./static:/app/static

  mysql-db:
    image: mysql:8
    container_name: communalert_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: communalert
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: communalert_phpmyadmin
    environment:
      PMA_HOST: mysql-db
      PMA_PORT: 3306
    ports:
      - "8080:80"
    depends_on:
      - mysql-db

volumes:
  mysql_data:
