"""Add new alert fields

Revision ID: 30d704aa3450
Revises: abcdef123456
Create Date: 2025-03-08 20:14:02.841348

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30d704aa3450'
down_revision: Union[str, None] = 'abcdef123456'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alerts', sa.Column('severity_level', sa.Enum('low', 'medium', 'high', name='severitylevel'), nullable=True))
    op.add_column('alerts', sa.Column('starting_date', sa.DateTime(), nullable=True))
    op.add_column('alerts', sa.Column('planned_duration', sa.Integer(), nullable=True))
    op.add_column('alerts', sa.Column('status', sa.Enum('open', 'closed', 'archived', name='alertstatus'), server_default='open', nullable=False))
    op.add_column('alerts', sa.Column('public_status', sa.Boolean(), nullable=True))
    op.add_column('alerts', sa.Column('longitude', sa.Float(), nullable=True))
    op.add_column('alerts', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('alerts', sa.Column('radius', sa.Float(), nullable=True))
    op.add_column('alerts', sa.Column('picture', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('alerts', 'picture')
    op.drop_column('alerts', 'radius')
    op.drop_column('alerts', 'latitude')
    op.drop_column('alerts', 'longitude')
    op.drop_column('alerts', 'public_status')
    op.drop_column('alerts', 'status')
    op.drop_column('alerts', 'planned_duration')
    op.drop_column('alerts', 'starting_date')
    op.drop_column('alerts', 'severity_level')
    # ### end Alembic commands ###
