"""Ajout relation messages dans User

Revision ID: 5008a63749f3
Revises: 37a44ae02fb7
Create Date: 2025-02-11 13:20:58.399645

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5008a63749f3'
down_revision: Union[str, None] = '37a44ae02fb7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('media_url', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'media_url')
    # ### end Alembic commands ###
